/* Lehrplan-Glossar für die Digitale Tafel
   ---------------------------------------
   Die Begriffe folgen den Lernbereichen des LehrplanPLUS Bayern, Gymnasium (G9),
   für Mathematik und Physik. Die Erklärungen sind eigene, schülergerechte
   Kurzfassungen – kein Zitat aus dem Lehrplan.
   Aufbau je Eintrag: [Fach, Jahrgangsstufe, Themenbereich, Begriff, Erklärung]
   Fach: 'M' = Mathematik, 'Ph' = Physik (Jgst. 7: Natur und Technik, Schwerpunkt Physik)
*/
window.LEHRPLAN = {
  stand: 'LehrplanPLUS Bayern, Gymnasium G9 – abgerufen im September 2026',
  hinweis: 'Begriffe nach den Lernbereichen des LehrplanPLUS; Erklärungen eigens verfasst.',
  faecher: { M:'Mathematik', Ph:'Physik' },
  e: [

/* ================= Mathematik 5 ================= */
['M',5,'Natürliche und ganze Zahlen','Natürliche Zahl','Zahl zum Zählen: 0, 1, 2, 3, … – die Reihe hört nie auf, es gibt also keine größte natürliche Zahl.'],
['M',5,'Natürliche und ganze Zahlen','Stellenwertsystem','Schreibweise, bei der der Wert einer Ziffer von ihrer Stelle abhängt; unser Zehnersystem bündelt immer zehn Einheiten zur nächsten Stelle.'],
['M',5,'Natürliche und ganze Zahlen','Zehnersystem','Stellenwertsystem mit den Ziffern 0 bis 9; jede Stelle ist zehnmal so viel wert wie die rechts daneben.'],
['M',5,'Natürliche und ganze Zahlen','Zahlenstrahl','Halbgerade mit gleichmäßiger Einteilung, auf der jede natürliche Zahl einen festen Platz hat.'],
['M',5,'Natürliche und ganze Zahlen','Zahlengerade','Gerade mit gleichmäßiger Einteilung, auf der auch die negativen Zahlen links von der Null liegen.'],
['M',5,'Natürliche und ganze Zahlen','Runden','Ersetzen einer Zahl durch einen Näherungswert; ab 5 wird aufgerundet, darunter abgerundet.'],
['M',5,'Natürliche und ganze Zahlen','Ganze Zahl','Zahl aus …, −2, −1, 0, 1, 2, … – die natürlichen Zahlen zusammen mit ihren negativen Gegenzahlen.'],
['M',5,'Natürliche und ganze Zahlen','Negative Zahl','Zahl kleiner als null, geschrieben mit Minuszeichen, z. B. −7; sie beschreibt etwa Schulden oder Temperaturen unter 0 °C.'],
['M',5,'Natürliche und ganze Zahlen','Betrag','Abstand einer Zahl von der Null auf der Zahlengeraden; er ist nie negativ, z. B. |−7| = 7.'],
['M',5,'Natürliche und ganze Zahlen','Gegenzahl','Zahl mit demselben Betrag, aber anderem Vorzeichen; die Gegenzahl von 5 ist −5.'],
['M',5,'Natürliche und ganze Zahlen','Vorzeichen','Das + oder − direkt vor einer Zahl; es sagt, auf welcher Seite der Null sie liegt.'],
['M',5,'Natürliche und ganze Zahlen','Rechenzeichen','Zeichen für eine Rechenart: +, −, · oder : – nicht zu verwechseln mit dem Vorzeichen einer Zahl.'],
['M',5,'Natürliche und ganze Zahlen','Summand','Zahl, die bei einer Addition addiert wird; das Ergebnis heißt Summe.'],
['M',5,'Natürliche und ganze Zahlen','Differenz','Ergebnis einer Subtraktion: Minuend minus Subtrahend.'],
['M',5,'Natürliche und ganze Zahlen','Faktor','Zahl, die bei einer Multiplikation malgenommen wird; das Ergebnis heißt Produkt.'],
['M',5,'Natürliche und ganze Zahlen','Quotient','Ergebnis einer Division: Dividend geteilt durch Divisor.'],
['M',5,'Natürliche und ganze Zahlen','Kommutativgesetz','Vertauschungsgesetz: Bei Addition und Multiplikation darf man die Reihenfolge tauschen, z. B. 3 + 8 = 8 + 3.'],
['M',5,'Natürliche und ganze Zahlen','Assoziativgesetz','Verbindungsgesetz: Bei Addition und Multiplikation darf man Klammern anders setzen, z. B. (2 + 5) + 8 = 2 + (5 + 8).'],
['M',5,'Natürliche und ganze Zahlen','Distributivgesetz','Verteilungsgesetz: a · (b + c) = a · b + a · c – eine Summe darf gliedweise malgenommen werden.'],
['M',5,'Natürliche und ganze Zahlen','Punkt vor Strich','Regel für die Reihenfolge: Malnehmen und Teilen wird vor Plus und Minus gerechnet, Klammern zuerst.'],
['M',5,'Natürliche und ganze Zahlen','Term','Rechenausdruck aus Zahlen, Rechenzeichen und Klammern, z. B. 3 · (7 − 2).'],
['M',5,'Natürliche und ganze Zahlen','Primfaktorzerlegung','Darstellung einer Zahl als Produkt von Primzahlen, z. B. 60 = 2 · 2 · 3 · 5; sie ist eindeutig.'],
['M',5,'Natürliche und ganze Zahlen','Teilbarkeit','Eine Zahl ist durch eine andere teilbar, wenn die Division ohne Rest aufgeht.'],
['M',5,'Natürliche und ganze Zahlen','Potenz','Kurzschreibweise für ein Produkt gleicher Faktoren: 2⁵ = 2 · 2 · 2 · 2 · 2; 2 ist die Basis, 5 der Exponent.'],
['M',5,'Natürliche und ganze Zahlen','Zehnerpotenz','Potenz mit der Basis 10, z. B. 10⁶ = 1 000 000; sie hilft beim Aufschreiben großer Zahlen.'],
['M',5,'Natürliche und ganze Zahlen','Quadratzahl','Ergebnis einer Zahl mal sich selbst, z. B. 1, 4, 9, 16, 25, …'],
['M',5,'Natürliche und ganze Zahlen','Baumdiagramm','Verzweigte Darstellung, mit der man alle Möglichkeiten eines mehrstufigen Vorgangs systematisch aufzählt.'],
['M',5,'Natürliche und ganze Zahlen','Überschlagsrechnung','Grobe Rechnung mit gerundeten Zahlen, um zu prüfen, ob ein Ergebnis plausibel ist.'],
['M',5,'Geometrische Figuren','Kartesisches Koordinatensystem','Zwei senkrecht aufeinander stehende Achsen; jeder Punkt wird durch ein Zahlenpaar (x | y) beschrieben.'],
['M',5,'Geometrische Figuren','Strecke','Der geradlinige Verbindungsweg zwischen zwei Punkten – begrenzt und mit messbarer Länge.'],
['M',5,'Geometrische Figuren','Gerade','Gerade Linie ohne Anfang und Ende, die in beide Richtungen unbegrenzt weiterläuft.'],
['M',5,'Geometrische Figuren','Parallel','Zwei Geraden heißen parallel, wenn sie überall denselben Abstand haben und sich nie schneiden.'],
['M',5,'Geometrische Figuren','Senkrecht','Zwei Geraden stehen senkrecht zueinander, wenn sie einen rechten Winkel (90°) bilden.'],
['M',5,'Geometrische Figuren','Lot','Strecke oder Gerade, die senkrecht auf eine andere Gerade trifft; sie liefert den kürzesten Abstand.'],
['M',5,'Geometrische Figuren','Abstand','Länge des kürzesten Weges – von Punkt zu Punkt geradlinig, von Punkt zu Gerade senkrecht.'],
['M',5,'Geometrische Figuren','Tangente','Gerade, die einen Kreis in genau einem Punkt berührt.'],
['M',5,'Geometrische Figuren','Winkel','Maß für die Drehung zwischen zwei Halbgeraden mit gemeinsamem Scheitel, gemessen in Grad.'],
['M',5,'Geometrische Figuren','Geodreieck','Zeichengerät mit Winkelskala und Parallelenlinien zum Messen und Zeichnen von Winkeln und Senkrechten.'],
['M',5,'Geometrische Figuren','Parallelogramm','Viereck, bei dem gegenüberliegende Seiten parallel und gleich lang sind.'],
['M',5,'Geometrische Figuren','Raute','Parallelogramm mit vier gleich langen Seiten.'],
['M',5,'Geometrische Figuren','Drachenviereck','Viereck mit zwei Paaren benachbarter gleich langer Seiten; seine Diagonalen stehen senkrecht aufeinander.'],
['M',5,'Geometrische Figuren','Trapez','Viereck mit mindestens einem Paar paralleler Seiten.'],
['M',5,'Größen und Einheiten','Größe','Angabe aus Maßzahl und Maßeinheit, z. B. 3,5 kg – die Zahl allein genügt nicht.'],
['M',5,'Größen und Einheiten','Maßzahl','Die Zahl einer Größenangabe, bei 3,5 kg also die 3,5.'],
['M',5,'Größen und Einheiten','Maßeinheit','Die Vergleichsgröße, mit der gemessen wird, z. B. m, kg oder s.'],
['M',5,'Größen und Einheiten','Messen','Vergleichen einer Größe mit einer Einheit: Wie oft passt die Einheit hinein?'],
['M',5,'Größen und Einheiten','Dreisatz','Rechenweg in drei Schritten: von der gegebenen Menge auf eine Einheit schließen, dann auf die gesuchte Menge.'],
['M',5,'Größen und Einheiten','Maßstab','Verhältnis von Bildlänge zu wirklicher Länge, z. B. 1 : 50 000 bei einer Landkarte.'],
['M',5,'Größen und Einheiten','Flächeninhalt','Maß für die Größe einer Fläche; beim Rechteck ist er Länge mal Breite.'],
['M',5,'Größen und Einheiten','Umfang','Gesamtlänge der Randlinie einer Figur.'],
['M',5,'Größen und Einheiten','Einheitsquadrat','Quadrat mit der Seitenlänge einer Längeneinheit, z. B. 1 cm; damit wird Flächeninhalt gemessen.'],
['M',5,'Größen und Einheiten','Hektar','Flächeneinheit für Felder und Wälder: 1 ha = 10 000 m², also ein Quadrat mit 100 m Seitenlänge.'],
['M',5,'Größen und Einheiten','Oberflächeninhalt','Gesamter Flächeninhalt aller Begrenzungsflächen eines Körpers.'],
['M',5,'Größen und Einheiten','Netz','Ebene Abwicklung eines Körpers: das aufgeklappte Modell aus Papier.'],
['M',5,'Größen und Einheiten','Schrägbild','Zeichnerische Darstellung eines Körpers, bei der Tiefenkanten schräg und verkürzt gezeichnet werden.'],
['M',5,'Größen und Einheiten','Quader','Körper aus sechs Rechtecken, bei dem gegenüberliegende Flächen gleich sind.'],

/* ================= Mathematik 6 ================= */
['M',6,'Rationale Zahlen','Bruch','Schreibweise a/b für einen Anteil oder eine Division; b heißt Nenner, a Zähler.'],
['M',6,'Rationale Zahlen','Zähler','Die Zahl über dem Bruchstrich: Sie sagt, wie viele der Teile gemeint sind.'],
['M',6,'Rationale Zahlen','Nenner','Die Zahl unter dem Bruchstrich: Sie sagt, in wie viele gleiche Teile das Ganze zerlegt wird.'],
['M',6,'Rationale Zahlen','Erweitern','Zähler und Nenner mit derselben Zahl malnehmen – der Wert des Bruchs bleibt gleich.'],
['M',6,'Rationale Zahlen','Kürzen','Zähler und Nenner durch dieselbe Zahl teilen – der Wert des Bruchs bleibt gleich.'],
['M',6,'Rationale Zahlen','Hauptnenner','Gemeinsamer Nenner mehrerer Brüche, meist das kleinste gemeinsame Vielfache der Nenner.'],
['M',6,'Rationale Zahlen','Gemischte Zahl','Schreibweise aus ganzer Zahl und Bruch, z. B. 2 3/4 statt 11/4.'],
['M',6,'Rationale Zahlen','Rationale Zahl','Zahl, die sich als Bruch ganzer Zahlen schreiben lässt – positiv wie negativ.'],
['M',6,'Rationale Zahlen','Dezimalbruch','Bruch in Kommaschreibweise, z. B. 0,75 statt 3/4.'],
['M',6,'Rationale Zahlen','Periodischer Dezimalbruch','Dezimalbruch, bei dem sich eine Ziffernfolge endlos wiederholt, z. B. 1/3 = 0,333… = 0,3̄.'],
['M',6,'Rationale Zahlen','Stellenwerttafel','Tabelle der Stellen von Tausendern bis Tausendsteln; sie zeigt, was jede Ziffer wert ist.'],
['M',6,'Rationale Zahlen','Anteil','Teil eines Ganzen, angegeben als Bruch, Dezimalzahl oder Prozentsatz.'],
['M',6,'Flächeninhalt und Volumen','Flächeninhalt des Dreiecks','A = ½ · g · h – Grundseite mal zugehörige Höhe, geteilt durch zwei.'],
['M',6,'Flächeninhalt und Volumen','Flächeninhalt des Parallelogramms','A = g · h – Grundseite mal die senkrecht dazu gemessene Höhe.'],
['M',6,'Flächeninhalt und Volumen','Flächeninhalt des Trapezes','A = ½ · (a + c) · h – Mittelwert der parallelen Seiten mal Höhe.'],
['M',6,'Flächeninhalt und Volumen','Höhe','Abstand einer Ecke oder Seite von der Grundseite, senkrecht gemessen.'],
['M',6,'Flächeninhalt und Volumen','Zerlegen und Ergänzen','Verfahren, eine Figur in bekannte Teilfiguren zu zerlegen oder zu einer solchen zu ergänzen.'],
['M',6,'Flächeninhalt und Volumen','Volumen','Maß für den Rauminhalt eines Körpers; beim Quader ist es Länge mal Breite mal Höhe.'],
['M',6,'Flächeninhalt und Volumen','Einheitswürfel','Würfel mit einer Längeneinheit Kantenlänge, z. B. 1 cm³; damit wird Volumen gemessen.'],
['M',6,'Flächeninhalt und Volumen','Liter','Hohlmaß für Volumen: 1 l = 1 dm³, 1 ml = 1 cm³.'],
['M',6,'Prozentrechnung und Daten','Prozent','Hundertstel: 1 % = 1/100; Prozentangaben vergleichen Anteile auf eine gemeinsame Basis.'],
['M',6,'Prozentrechnung und Daten','Grundwert','Das Ganze, auf das sich ein Prozentsatz bezieht (100 %).'],
['M',6,'Prozentrechnung und Daten','Prozentwert','Der Anteil, der zum Prozentsatz gehört: Prozentwert = Grundwert · Prozentsatz.'],
['M',6,'Prozentrechnung und Daten','Prozentsatz','Angabe des Anteils in Hundertsteln, z. B. 20 %.'],
['M',6,'Prozentrechnung und Daten','Prozentpunkt','Differenz zweier Prozentsätze: von 40 % auf 45 % sind 5 Prozentpunkte, aber 12,5 % Zuwachs.'],
['M',6,'Prozentrechnung und Daten','Rabatt','Preisnachlass, meist als Prozentsatz des ursprünglichen Preises angegeben.'],
['M',6,'Prozentrechnung und Daten','Absolute Häufigkeit','Anzahl, wie oft ein Ergebnis vorkommt.'],
['M',6,'Prozentrechnung und Daten','Relative Häufigkeit','Anteil eines Ergebnisses an allen Fällen – als Bruch, Dezimalzahl oder Prozentsatz.'],
['M',6,'Prozentrechnung und Daten','Arithmetisches Mittel','Durchschnitt: Summe aller Werte geteilt durch ihre Anzahl.'],
['M',6,'Prozentrechnung und Daten','Kreisdiagramm','Diagramm, bei dem Anteile als Sektoren eines Kreises dargestellt werden.'],
['M',6,'Prozentrechnung und Daten','Säulendiagramm','Diagramm, bei dem Häufigkeiten als unterschiedlich hohe Säulen dargestellt werden.'],

/* ================= Mathematik 7 ================= */
['M',7,'Terme mit Variablen','Variable','Platzhalter für eine Zahl, meist ein Buchstabe wie x oder a.'],
['M',7,'Terme mit Variablen','Wertetabelle','Tabelle, die zu eingesetzten Zahlen die zugehörigen Termwerte auflistet.'],
['M',7,'Terme mit Variablen','Äquivalente Terme','Terme, die für jede eingesetzte Zahl denselben Wert liefern.'],
['M',7,'Terme mit Variablen','Ausmultiplizieren','Eine Klammer auflösen, indem jeder Summand mit dem Faktor malgenommen wird.'],
['M',7,'Terme mit Variablen','Ausklammern','Einen gemeinsamen Faktor vor die Klammer ziehen – aus einer Summe wird ein Produkt.'],
['M',7,'Terme mit Variablen','Faktorisieren','Einen Term als Produkt schreiben, z. B. 6x + 9 = 3 · (2x + 3).'],
['M',7,'Terme mit Variablen','Binomische Formel','Merkformel für Quadrate von Summen: (a + b)² = a² + 2ab + b², (a − b)² = a² − 2ab + b², (a + b)(a − b) = a² − b².'],
['M',7,'Terme mit Variablen','Potenzgesetz','Regel zum Zusammenfassen von Potenzen, z. B. a^m · a^n = a^(m+n).'],
['M',7,'Symmetrie und Winkel','Achsensymmetrie','Eigenschaft einer Figur, die beim Spiegeln an einer Geraden auf sich selbst fällt.'],
['M',7,'Symmetrie und Winkel','Punktsymmetrie','Eigenschaft einer Figur, die bei Drehung um 180° um einen Punkt auf sich selbst fällt.'],
['M',7,'Symmetrie und Winkel','Symmetrieachse','Die Gerade, an der eine achsensymmetrische Figur gespiegelt wird.'],
['M',7,'Symmetrie und Winkel','Symmetriezentrum','Der Punkt, um den eine punktsymmetrische Figur gedreht wird.'],
['M',7,'Symmetrie und Winkel','Mittelsenkrechte','Gerade, die eine Strecke senkrecht halbiert; alle ihre Punkte haben von beiden Endpunkten denselben Abstand.'],
['M',7,'Symmetrie und Winkel','Winkelhalbierende','Gerade, die einen Winkel in zwei gleich große Teile teilt; ihre Punkte sind von beiden Schenkeln gleich weit entfernt.'],
['M',7,'Symmetrie und Winkel','Scheitelwinkel','Winkel, die sich an einer Geradenkreuzung gegenüberliegen – sie sind gleich groß.'],
['M',7,'Symmetrie und Winkel','Nebenwinkel','Winkel, die an einer Kreuzung nebeneinanderliegen – zusammen ergeben sie 180°.'],
['M',7,'Symmetrie und Winkel','Stufenwinkel','Gleichliegende Winkel an zwei parallelen Geraden mit einer Schnittgeraden – sie sind gleich groß.'],
['M',7,'Symmetrie und Winkel','Wechselwinkel','Wechselseitig liegende Winkel an parallelen Geraden – sie sind ebenfalls gleich groß.'],
['M',7,'Symmetrie und Winkel','Innenwinkelsumme','Summe der Innenwinkel einer Figur; im Dreieck beträgt sie stets 180°.'],
['M',7,'Lineare Gleichungen','Gleichung','Aussage, dass zwei Terme denselben Wert haben, verbunden durch das Gleichheitszeichen.'],
['M',7,'Lineare Gleichungen','Äquivalenzumformung','Umformung einer Gleichung, die die Lösungsmenge nicht verändert – auf beiden Seiten dasselbe tun.'],
['M',7,'Lineare Gleichungen','Lösungsmenge','Menge aller Zahlen, die eine Gleichung erfüllen.'],
['M',7,'Lineare Gleichungen','Probe','Einsetzen der gefundenen Lösung in die ursprüngliche Gleichung zur Kontrolle.'],
['M',7,'Kenngrößen von Daten','Median','Mittlerer Wert einer der Größe nach geordneten Datenreihe; er ist unempfindlich gegen Ausreißer.'],
['M',7,'Kenngrößen von Daten','Spannweite','Differenz zwischen größtem und kleinstem Wert eines Datensatzes.'],
['M',7,'Kenngrößen von Daten','Quartil','Wert, der die geordneten Daten in Viertel teilt; das 2. Quartil ist der Median.'],
['M',7,'Kenngrößen von Daten','Boxplot','Kastengrafik aus Minimum, unterem Quartil, Median, oberem Quartil und Maximum.'],
['M',7,'Kongruenz und Dreiecke','Kongruenz','Deckungsgleichheit: Zwei Figuren sind kongruent, wenn sie durch Verschieben, Drehen oder Spiegeln zur Deckung kommen.'],
['M',7,'Kongruenz und Dreiecke','Kongruenzsatz','Regel, welche Angaben ein Dreieck eindeutig festlegen: SSS, SWS, WSW und SsW.'],
['M',7,'Kongruenz und Dreiecke','Gleichschenkliges Dreieck','Dreieck mit zwei gleich langen Seiten; die Winkel an der Basis sind gleich groß.'],
['M',7,'Kongruenz und Dreiecke','Gleichseitiges Dreieck','Dreieck mit drei gleich langen Seiten und drei 60°-Winkeln.'],
['M',7,'Kongruenz und Dreiecke','Satz des Thales','Liegt der Punkt C auf dem Kreis über der Strecke AB als Durchmesser, so ist der Winkel bei C ein rechter.'],
['M',7,'Kongruenz und Dreiecke','Umkreis','Kreis durch alle drei Ecken eines Dreiecks; sein Mittelpunkt ist der Schnittpunkt der Mittelsenkrechten.'],
['M',7,'Kongruenz und Dreiecke','Inkreis','Kreis, der alle drei Seiten eines Dreiecks berührt; sein Mittelpunkt ist der Schnittpunkt der Winkelhalbierenden.'],
['M',7,'Kongruenz und Dreiecke','Voraussetzung','Der Teil eines Satzes, der gegeben ist – daraus folgt die Behauptung.'],
['M',7,'Kongruenz und Dreiecke','Kehrsatz','Umkehrung eines Satzes: Voraussetzung und Behauptung werden getauscht; sie muss nicht wahr sein.'],

/* ================= Mathematik 8 ================= */
['M',8,'Funktionen','Funktion','Eindeutige Zuordnung: Jedem x-Wert wird genau ein y-Wert zugeordnet.'],
['M',8,'Funktionen','Funktionsterm','Rechenvorschrift einer Funktion, z. B. f(x) = 2x + 3.'],
['M',8,'Funktionen','Graph','Bild einer Funktion im Koordinatensystem – die Menge aller Punkte (x | f(x)).'],
['M',8,'Funktionen','Definitionsmenge','Menge aller x-Werte, die man einsetzen darf.'],
['M',8,'Funktionen','Wertemenge','Menge aller y-Werte, die die Funktion annimmt.'],
['M',8,'Funktionen','Nullstelle','x-Wert, an dem der Graph die x-Achse schneidet, also f(x) = 0.'],
['M',8,'Lineare Funktionen','Lineare Funktion','Funktion mit der Gleichung y = m · x + t; ihr Graph ist eine Gerade.'],
['M',8,'Lineare Funktionen','Steigung','Der Wert m einer Geraden: Wie viel y sich ändert, wenn x um 1 wächst.'],
['M',8,'Lineare Funktionen','y-Achsenabschnitt','Der Wert t: die Höhe, in der die Gerade die y-Achse schneidet.'],
['M',8,'Lineare Funktionen','Direkte Proportionalität','Zusammenhang y = a · x: Das Doppelte gehört zum Doppelten; der Graph ist eine Ursprungsgerade.'],
['M',8,'Lineare Funktionen','Ursprungsgerade','Gerade durch den Koordinatenursprung, also mit t = 0.'],
['M',8,'Lineare Funktionen','Ungleichung','Aussage mit <, >, ≤ oder ≥ statt des Gleichheitszeichens.'],
['M',8,'Lineare Funktionen','Intervall','Zusammenhängender Bereich von Zahlen, z. B. [2; 5] oder x > 3.'],
['M',8,'Gebrochen-rationale Funktionen','Gebrochen-rationale Funktion','Funktion, deren Term einen Bruch mit der Variablen im Nenner enthält.'],
['M',8,'Gebrochen-rationale Funktionen','Definitionslücke','x-Wert, der nicht eingesetzt werden darf, weil der Nenner null würde.'],
['M',8,'Gebrochen-rationale Funktionen','Asymptote','Gerade, der sich ein Graph immer weiter annähert, ohne sie zu erreichen.'],
['M',8,'Gebrochen-rationale Funktionen','Hyperbel','Graph der Funktion y = a/x – zwei getrennte, gebogene Äste.'],
['M',8,'Gebrochen-rationale Funktionen','Indirekte Proportionalität','Zusammenhang y = a/x: Das Doppelte gehört zur Hälfte; das Produkt x · y bleibt gleich.'],
['M',8,'Bruchterme','Bruchterm','Term, bei dem eine Variable im Nenner steht, z. B. 3/(x − 2).'],
['M',8,'Bruchterme','Bruchgleichung','Gleichung, in der die Unbekannte im Nenner vorkommt; die Definitionsmenge muss beachtet werden.'],
['M',8,'Bruchterme','Formel umstellen','Eine Formel durch Äquivalenzumformungen nach einer gesuchten Größe auflösen.'],
['M',8,'Laplace-Experimente','Zufallsexperiment','Vorgang mit mehreren möglichen Ergebnissen, dessen Ausgang nicht vorhersagbar ist.'],
['M',8,'Laplace-Experimente','Ergebnismenge','Menge aller möglichen Ergebnisse eines Zufallsexperiments.'],
['M',8,'Laplace-Experimente','Ereignis','Zusammenfassung von Ergebnissen, z. B. „gerade Augenzahl".'],
['M',8,'Laplace-Experimente','Gegenereignis','Alles, was nicht zum Ereignis gehört; seine Wahrscheinlichkeit ist 1 minus die des Ereignisses.'],
['M',8,'Laplace-Experimente','Laplace-Experiment','Zufallsexperiment, bei dem alle Ergebnisse gleich wahrscheinlich sind.'],
['M',8,'Laplace-Experimente','Laplace-Wahrscheinlichkeit','P(E) = Anzahl der günstigen Ergebnisse geteilt durch Anzahl aller Ergebnisse.'],
['M',8,'Laplace-Experimente','Gesetz der großen Zahlen','Je öfter man ein Zufallsexperiment durchführt, desto näher liegt die relative Häufigkeit bei der Wahrscheinlichkeit.'],
['M',8,'Lineare Gleichungssysteme','Lineares Gleichungssystem','Mehrere lineare Gleichungen, die gleichzeitig erfüllt sein müssen.'],
['M',8,'Lineare Gleichungssysteme','Einsetzungsverfahren','Lösungsweg: eine Gleichung nach einer Variablen auflösen und in die andere einsetzen.'],
['M',8,'Kreis und Zylinder','Kreiszahl π','Verhältnis von Umfang zu Durchmesser eines Kreises, ungefähr 3,14159.'],
['M',8,'Kreis und Zylinder','Kreisumfang','U = 2 · π · r – der Rand des Kreises.'],
['M',8,'Kreis und Zylinder','Kreisfläche','A = π · r² – der Flächeninhalt des Kreises.'],
['M',8,'Kreis und Zylinder','Prisma','Körper mit zwei gleichen, parallelen Grundflächen und rechteckigen Seitenflächen; V = G · h.'],
['M',8,'Kreis und Zylinder','Zylinder','Körper mit zwei kreisförmigen Grundflächen; V = π · r² · h.'],
['M',8,'Kreis und Zylinder','Mantelfläche','Die gekrümmte Seitenfläche eines Zylinders; abgewickelt ist sie ein Rechteck.'],

/* ================= Mathematik 9 ================= */
['M',9,'Quadratwurzeln','Quadratwurzel','√a ist die nichtnegative Zahl, deren Quadrat a ergibt.'],
['M',9,'Quadratwurzeln','Radikand','Die Zahl unter dem Wurzelzeichen.'],
['M',9,'Quadratwurzeln','Irrationale Zahl','Zahl, die sich nicht als Bruch schreiben lässt, z. B. √2 oder π; ihre Dezimaldarstellung bricht nie ab und ist nicht periodisch.'],
['M',9,'Quadratwurzeln','Reelle Zahl','Alle rationalen und irrationalen Zahlen zusammen – sie füllen die Zahlengerade lückenlos.'],
['M',9,'Quadratwurzeln','Indirekter Beweis','Beweis durch Widerspruch: Man nimmt das Gegenteil an und führt es zu einem Widerspruch.'],
['M',9,'Quadratwurzeln','Heron-Verfahren','Näherungsverfahren für Wurzeln: Mittelwert aus Schätzwert und Radikand geteilt durch Schätzwert, mehrfach wiederholt.'],
['M',9,'Quadratwurzeln','Teilweises Radizieren','Umformen wie √50 = √25 · √2 = 5√2, um die Wurzel zu vereinfachen.'],
['M',9,'Quadratische Funktionen','Quadratische Funktion','Funktion mit der Gleichung y = ax² + bx + c (a ≠ 0); ihr Graph ist eine Parabel.'],
['M',9,'Quadratische Funktionen','Parabel','Gebogener Graph einer quadratischen Funktion, symmetrisch zu einer senkrechten Achse.'],
['M',9,'Quadratische Funktionen','Scheitel','Höchster oder tiefster Punkt einer Parabel.'],
['M',9,'Quadratische Funktionen','Scheitelpunktform','Darstellung y = a · (x − x_S)² + y_S; daran liest man den Scheitel direkt ab.'],
['M',9,'Quadratische Funktionen','Nullstellenform','Darstellung y = a · (x − x₁) · (x − x₂); daran liest man die Nullstellen direkt ab.'],
['M',9,'Quadratische Funktionen','Lösungsformel','Mitternachtsformel zur Lösung von ax² + bx + c = 0: x = (−b ± √(b² − 4ac)) / (2a).'],
['M',9,'Quadratische Funktionen','Diskriminante','Der Wert b² − 4ac; sein Vorzeichen entscheidet über die Anzahl der Lösungen.'],
['M',9,'Quadratische Funktionen','Monotonie','Verhalten eines Graphen: streng steigend oder fallend in einem Bereich.'],
['M',9,'Quadratische Funktionen','Extremwertproblem','Aufgabe, bei der ein größter oder kleinster Wert gesucht wird, z. B. die größte Fläche bei gegebenem Umfang.'],
['M',9,'Wahrscheinlichkeit','Vierfeldertafel','Tabelle, die zwei Ereignisse und ihre Gegenereignisse kreuzweise gegenüberstellt.'],
['M',9,'Wahrscheinlichkeit','Schnittmenge','Ereignis „A und B": alle Ergebnisse, die zu beiden Ereignissen gehören (A ∩ B).'],
['M',9,'Wahrscheinlichkeit','Vereinigungsmenge','Ereignis „A oder B": alle Ergebnisse, die zu mindestens einem der Ereignisse gehören (A ∪ B).'],
['M',9,'Wahrscheinlichkeit','Additionssatz','P(A ∪ B) = P(A) + P(B) − P(A ∩ B) – der gemeinsame Teil wird einmal abgezogen.'],
['M',9,'Ähnlichkeit','Ähnlichkeit','Zwei Figuren sind ähnlich, wenn sie in allen Winkeln übereinstimmen und ihre Seiten dasselbe Verhältnis haben.'],
['M',9,'Ähnlichkeit','Strahlensatz','Satz über Streckenverhältnisse an zwei Strahlen mit parallelen Geraden – Grundlage vieler Messverfahren.'],
['M',9,'Ähnlichkeit','Streckfaktor','Zahl k, mit der alle Längen vervielfacht werden; Flächen wachsen dabei mit k², Volumina mit k³.'],
['M',9,'Potenzfunktionen','Potenzfunktion','Funktion mit dem Term a · xⁿ; für gerade n ist der Graph achsensymmetrisch, für ungerade punktsymmetrisch.'],
['M',9,'Potenzfunktionen','n-te Wurzel','Umkehrung des Potenzierens: die Zahl, deren n-te Potenz den Radikanden ergibt.'],
['M',9,'Potenzfunktionen','Rationaler Exponent','Schreibweise wie a^(1/2) = √a – Wurzeln lassen sich als Potenzen schreiben.'],
['M',9,'Satz des Pythagoras','Satz des Pythagoras','Im rechtwinkligen Dreieck gilt a² + b² = c²: Die Quadrate über den Katheten ergeben zusammen das Quadrat über der Hypotenuse.'],
['M',9,'Satz des Pythagoras','Hypotenuse','Die längste Seite im rechtwinkligen Dreieck – sie liegt dem rechten Winkel gegenüber.'],
['M',9,'Satz des Pythagoras','Kathete','Eine der beiden Seiten, die den rechten Winkel einschließen.'],
['M',9,'Trigonometrie','Sinus','Im rechtwinkligen Dreieck: Gegenkathete geteilt durch Hypotenuse.'],
['M',9,'Trigonometrie','Kosinus','Im rechtwinkligen Dreieck: Ankathete geteilt durch Hypotenuse.'],
['M',9,'Trigonometrie','Tangens','Im rechtwinkligen Dreieck: Gegenkathete geteilt durch Ankathete.'],
['M',9,'Trigonometrie','Einheitskreis','Kreis mit Radius 1 um den Ursprung; an ihm liest man Sinus und Kosinus für alle Winkel ab.'],
['M',9,'Trigonometrie','Sinussatz','In jedem Dreieck gilt a : sin α = b : sin β = c : sin γ.'],
['M',9,'Trigonometrie','Kosinussatz','c² = a² + b² − 2ab · cos γ – die Verallgemeinerung des Satzes von Pythagoras.'],
['M',9,'Trigonometrie','Trigonometrischer Pythagoras','Für jeden Winkel gilt (sin α)² + (cos α)² = 1.'],

/* ================= Mathematik 10 ================= */
['M',10,'Exponentielles Wachstum','Exponentielles Wachstum','Wachstum, bei dem sich der Bestand in gleichen Zeitschritten immer mit demselben Faktor ändert.'],
['M',10,'Exponentielles Wachstum','Exponentialfunktion','Funktion mit dem Term b · aˣ; die Variable steht im Exponenten.'],
['M',10,'Exponentielles Wachstum','Wachstumsfaktor','Die Zahl a, mit der pro Zeitschritt multipliziert wird; a > 1 bedeutet Zunahme, 0 < a < 1 Abnahme.'],
['M',10,'Exponentielles Wachstum','Logarithmus','Die Hochzahl, mit der man die Basis potenzieren muss: log_b(u) = z bedeutet b^z = u.'],
['M',10,'Exponentielles Wachstum','Halbwertszeit','Zeitspanne, nach der nur noch die Hälfte des Ausgangsbestands vorhanden ist, z. B. beim radioaktiven Zerfall.'],
['M',10,'Exponentielles Wachstum','Exponentialgleichung','Gleichung, bei der die Unbekannte im Exponenten steht; man löst sie mit dem Logarithmus.'],
['M',10,'Zufallsexperimente','Mehrstufiges Zufallsexperiment','Zufallsversuch aus mehreren Teilversuchen, dargestellt im Baumdiagramm.'],
['M',10,'Zufallsexperimente','Pfadregel','Entlang eines Pfades multiplizieren, mehrere Pfade addieren.'],
['M',10,'Zufallsexperimente','Urnenmodell','Modellvorstellung mit Kugeln in einer Urne – mit oder ohne Zurücklegen.'],
['M',10,'Zufallsexperimente','Monte-Carlo-Methode','Näherungsverfahren, das mit vielen Zufallsversuchen rechnet, z. B. zur Bestimmung von π.'],
['M',10,'Zufallsexperimente','Simulation','Nachbilden eines Zufallsvorgangs mit Zufallszahlen, um Wahrscheinlichkeiten abzuschätzen.'],
['M',10,'Sinus- und Kosinusfunktion','Bogenmaß','Winkelmaß über die Bogenlänge am Einheitskreis; 180° entsprechen π.'],
['M',10,'Sinus- und Kosinusfunktion','Periode','Länge des Abschnitts, nach dem sich ein Funktionsgraph wiederholt.'],
['M',10,'Sinus- und Kosinusfunktion','Amplitude','Halbe Höhe zwischen Hoch- und Tiefpunkt einer Sinuskurve – der Faktor a.'],
['M',10,'Sinus- und Kosinusfunktion','Periodizität','Eigenschaft einer Funktion, sich in gleichen Abständen zu wiederholen.'],
['M',10,'Ganzrationale Funktionen','Ganzrationale Funktion','Summe von Potenzen mit natürlichen Exponenten, z. B. f(x) = 2x³ − x + 5.'],
['M',10,'Ganzrationale Funktionen','Grad','Höchster Exponent im Funktionsterm; er bestimmt das Verhalten für große |x|.'],
['M',10,'Ganzrationale Funktionen','Vielfachheit einer Nullstelle','Wie oft ein Linearfaktor vorkommt; sie entscheidet, ob der Graph die Achse schneidet oder berührt.'],
['M',10,'Ganzrationale Funktionen','Substitution','Ersetzen eines Terms durch eine neue Variable, z. B. u = x² bei biquadratischen Gleichungen.'],
['M',10,'Raumgeometrie','Pyramide','Körper mit einer Vieleck-Grundfläche und einer Spitze; V = ⅓ · G · h.'],
['M',10,'Raumgeometrie','Kegel','Körper mit Kreisgrundfläche und Spitze; V = ⅓ · π · r² · h.'],
['M',10,'Raumgeometrie','Kugel','Körper aller Punkte mit gleichem Abstand vom Mittelpunkt; V = 4/3 · π · r³, O = 4 · π · r².'],
['M',10,'Raumgeometrie','Rotationskörper','Körper, der beim Drehen einer Fläche um eine Achse entsteht, z. B. Zylinder, Kegel, Kugel.'],
['M',10,'Raumgeometrie','Prinzip von Cavalieri','Körper gleicher Höhe mit in jeder Höhe gleich großen Querschnitten haben dasselbe Volumen.'],

/* ================= Mathematik 11 ================= */
['M',11,'Eigenschaften von Funktionen','Grenzwert','Wert, dem sich die Funktionswerte beliebig genau nähern; Schreibweise lim.'],
['M',11,'Eigenschaften von Funktionen','Konvergenz','Verhalten einer Funktion oder Folge, die sich einem festen Wert nähert.'],
['M',11,'Eigenschaften von Funktionen','Divergenz','Verhalten ohne Annäherung an einen festen Wert, z. B. unbegrenztes Wachsen.'],
['M',11,'Eigenschaften von Funktionen','Stetigkeit','Anschaulich: Der Graph lässt sich ohne Absetzen zeichnen.'],
['M',11,'Eigenschaften von Funktionen','Transformation','Verschieben, Strecken oder Spiegeln eines Graphen durch Änderung des Funktionsterms.'],
['M',11,'Gebrochen-rationale Funktionen','Polstelle','Definitionslücke, an der die Funktionswerte über alle Grenzen wachsen oder fallen.'],
['M',11,'Gebrochen-rationale Funktionen','Senkrechte Asymptote','Senkrechte Gerade an einer Polstelle, der sich der Graph annähert.'],
['M',11,'Gebrochen-rationale Funktionen','Waagrechte Asymptote','Waagrechte Gerade, der sich der Graph für sehr große oder sehr kleine x nähert.'],
['M',11,'Gebrochen-rationale Funktionen','Linearfaktor','Faktor der Form (x − a); er gehört zur Nullstelle a.'],
['M',11,'Bedingte Wahrscheinlichkeit','Bedingte Wahrscheinlichkeit','Wahrscheinlichkeit eines Ereignisses unter der Bedingung, dass ein anderes schon eingetreten ist: P_B(A).'],
['M',11,'Bedingte Wahrscheinlichkeit','Stochastische Unabhängigkeit','Zwei Ereignisse sind unabhängig, wenn P(A ∩ B) = P(A) · P(B) gilt.'],
['M',11,'Bedingte Wahrscheinlichkeit','Korrelation','Statistischer Zusammenhang zweier Merkmale – er bedeutet noch keine Ursache.'],
['M',11,'Bedingte Wahrscheinlichkeit','Kausalität','Ursache-Wirkungs-Beziehung; sie muss eigens begründet werden.'],
['M',11,'Differentialrechnung','Differenzenquotient','Mittlere Änderungsrate: (f(b) − f(a)) / (b − a) – geometrisch die Sekantensteigung.'],
['M',11,'Differentialrechnung','Differentialquotient','Grenzwert des Differenzenquotienten – geometrisch die Tangentensteigung.'],
['M',11,'Differentialrechnung','Ableitung','Funktion, die zu jeder Stelle die Steigung des Graphen angibt.'],
['M',11,'Differentialrechnung','Momentane Änderungsrate','Wert der Ableitung an einer Stelle, z. B. die Momentangeschwindigkeit.'],
['M',11,'Differentialrechnung','Tangente','Gerade, die den Graphen in einem Punkt berührt und dort dieselbe Steigung hat.'],
['M',11,'Differentialrechnung','Sekante','Gerade durch zwei Punkte eines Graphen.'],
['M',11,'Differentialrechnung','Extremstelle','Stelle mit Hoch- oder Tiefpunkt; notwendig ist dort f′(x) = 0.'],
['M',11,'Differentialrechnung','Wendestelle','Stelle, an der der Graph seine Krümmung wechselt; dort ist die Steigung extremal.'],
['M',11,'Differentialrechnung','Krümmung','Verhalten des Graphen: linksgekrümmt bei f″ > 0, rechtsgekrümmt bei f″ < 0.'],
['M',11,'Differentialrechnung','Notwendige Bedingung','Bedingung, die erfüllt sein muss, aber allein noch nicht ausreicht.'],
['M',11,'Differentialrechnung','Hinreichende Bedingung','Bedingung, aus der die Aussage sicher folgt.'],
['M',11,'Differentialrechnung','Newton-Verfahren','Näherungsverfahren für Nullstellen mithilfe von Tangenten, schrittweise wiederholt.'],

/* ================= Mathematik 13 ================= */
['M',13,'Integralrechnung','Bestimmtes Integral','Flächenbilanz zwischen Graph und x-Achse in einem Intervall – Flächen unterhalb zählen negativ.'],
['M',13,'Integralrechnung','Stammfunktion','Funktion F mit F′ = f; sie ist bis auf eine additive Konstante eindeutig.'],
['M',13,'Integralrechnung','Integralfunktion','Funktion, die jedem oberen Grenzwert den Wert des Integrals ab einer festen unteren Grenze zuordnet.'],
['M',13,'Integralrechnung','Hauptsatz','Hauptsatz der Differential- und Integralrechnung: Integrieren und Ableiten sind Umkehrungen voneinander.'],
['M',13,'Integralrechnung','Uneigentliches Integral','Integral mit unendlicher Grenze oder unbeschränktem Integranden, über einen Grenzwert erklärt.'],
['M',13,'Integralrechnung','Rotationsvolumen','Volumen des Körpers, der beim Drehen eines Graphen um die x-Achse entsteht: V = π ∫ f(x)² dx.'],
['M',13,'Normalverteilung','Zufallsgröße','Größe, die jedem Ergebnis eines Zufallsexperiments eine Zahl zuordnet.'],
['M',13,'Normalverteilung','Erwartungswert','Durchschnittlich zu erwartender Wert einer Zufallsgröße auf lange Sicht.'],
['M',13,'Normalverteilung','Standardabweichung','Maß für die Streuung der Werte um den Erwartungswert.'],
['M',13,'Normalverteilung','Normalverteilung','Glockenförmige Verteilung, die bei vielen Messwerten näherungsweise auftritt.'],
['M',13,'Normalverteilung','Dichtefunktion','Funktion, deren Flächeninhalt unter dem Graphen Wahrscheinlichkeiten angibt.'],
['M',13,'Normalverteilung','Sigma-Regel','Faustregel: rund 68 %, 95,4 % bzw. 99,7 % der Werte liegen im 1-, 2- bzw. 3-Sigma-Intervall.'],
['M',13,'Geraden und Ebenen','Vektor','Größe mit Betrag und Richtung, dargestellt als Pfeil oder Zahlentripel.'],
['M',13,'Geraden und Ebenen','Linearkombination','Summe von Vielfachen mehrerer Vektoren.'],
['M',13,'Geraden und Ebenen','Lineare Unabhängigkeit','Vektoren sind linear unabhängig, wenn keiner sich aus den anderen kombinieren lässt.'],
['M',13,'Geraden und Ebenen','Parameterform','Geraden- oder Ebenengleichung aus Stützvektor und Richtungsvektoren.'],
['M',13,'Geraden und Ebenen','Normalenvektor','Vektor, der senkrecht auf einer Ebene steht.'],
['M',13,'Geraden und Ebenen','Koordinatenform','Ebenengleichung der Form ax + by + cz = d.'],
['M',13,'Geraden und Ebenen','Windschief','Lagebeziehung zweier Geraden, die weder parallel sind noch sich schneiden.'],
['M',13,'Geraden und Ebenen','Hesse-Normalform','Normierte Ebenengleichung; damit berechnet man Abstände unmittelbar.'],
['M',13,'Geraden und Ebenen','Kugelgleichung','Gleichung aller Punkte mit festem Abstand r vom Mittelpunkt M.'],

/* ============ Physik 7 (Natur und Technik, Schwerpunkt Physik) ============ */
['Ph',7,'Magnetismus und Dichte','Permanentmagnet','Dauermagnet, der seine magnetische Wirkung ohne Strom behält; er hat immer Nord- und Südpol.'],
['Ph',7,'Magnetismus und Dichte','Elementarmagnet','Modellvorstellung winziger Magnete im Material; sind sie geordnet, ist der Körper magnetisch.'],
['Ph',7,'Magnetismus und Dichte','Erdmagnetfeld','Magnetfeld der Erde; es richtet die Kompassnadel nach Norden aus.'],
['Ph',7,'Magnetismus und Dichte','Dichte','Masse je Volumen: ρ = m / V; sie ist für jedes Material charakteristisch.'],
['Ph',7,'Magnetismus und Dichte','Versuchsprotokoll','Geordnete Aufzeichnung von Aufbau, Durchführung, Beobachtung und Auswertung eines Experiments.'],
['Ph',7,'Optische Phänomene','Lichtquelle','Körper, der selbst Licht aussendet – im Gegensatz zum beleuchteten Körper.'],
['Ph',7,'Optische Phänomene','Sehvorgang','Licht geht von einer Quelle aus, wird an Gegenständen zurückgeworfen und gelangt ins Auge.'],
['Ph',7,'Optische Phänomene','Geradlinige Lichtausbreitung','In einem gleichmäßigen Stoff breitet sich Licht geradlinig aus – daher entstehen scharfe Schatten.'],
['Ph',7,'Optische Phänomene','Kernschatten','Bereich, in den überhaupt kein Licht der Quelle gelangt.'],
['Ph',7,'Optische Phänomene','Halbschatten','Bereich, den nur ein Teil einer ausgedehnten Lichtquelle beleuchtet.'],
['Ph',7,'Optische Phänomene','Mondphasen','Wechselnde Gestalt des Mondes, weil wir je nach Stellung einen anderen Teil der beleuchteten Hälfte sehen.'],
['Ph',7,'Optische Phänomene','Sonnenfinsternis','Der Mond steht zwischen Sonne und Erde und wirft seinen Schatten auf die Erde.'],
['Ph',7,'Optische Phänomene','Mondfinsternis','Die Erde steht zwischen Sonne und Mond; der Mond taucht in den Erdschatten.'],
['Ph',7,'Optische Phänomene','Absorption','Aufnahme von Licht durch einen Körper; das nicht absorbierte Licht bestimmt seine Farbe.'],
['Ph',7,'Elektrische Stromkreise','Elektrische Ladung','Grundeigenschaft der Materie in zwei Arten: Gleiche Ladungen stoßen sich ab, ungleiche ziehen sich an.'],
['Ph',7,'Elektrische Stromkreise','Kern-Hülle-Modell','Modell des Atoms: positiver Kern, umgeben von negativ geladenen Elektronen in der Hülle.'],
['Ph',7,'Elektrische Stromkreise','Elektrischer Strom','Gerichtete Bewegung von Ladungen, z. B. von Elektronen im Draht.'],
['Ph',7,'Elektrische Stromkreise','Reibungselektrizität','Ladungstrennung durch Reiben zweier Stoffe, z. B. Luftballon an Haaren.'],
['Ph',7,'Elektrische Stromkreise','Stromkreis','Geschlossener Weg für den Strom von der Quelle über den Verbraucher und zurück.'],

/* ================= Physik 8 ================= */
['Ph',8,'Elektrischer Strom','Elektrische Stromstärke','Größe für die Menge an Ladung, die je Zeit durch einen Querschnitt fließt; Einheit Ampere (A).'],
['Ph',8,'Elektrischer Strom','Elektrische Spannung','Antrieb für den elektrischen Strom; Einheit Volt (V).'],
['Ph',8,'Elektrischer Strom','Elektrischer Widerstand','R = U / I – Maß dafür, wie stark ein Bauteil den Strom hemmt; Einheit Ohm (Ω).'],
['Ph',8,'Elektrischer Strom','Kennlinie','Diagramm, das zu jeder Spannung die zugehörige Stromstärke eines Bauteils zeigt.'],
['Ph',8,'Elektrischer Strom','Ohmscher Widerstand','Bauteil, bei dem Stromstärke und Spannung zueinander proportional sind – die Kennlinie ist eine Gerade.'],
['Ph',8,'Elektrischer Strom','Leiter','Stoff, in dem sich Ladungen gut bewegen können, z. B. Metall.'],
['Ph',8,'Elektrischer Strom','Isolator','Stoff, in dem sich Ladungen kaum bewegen, z. B. Kunststoff.'],
['Ph',8,'Elektrischer Strom','Kurzschluss','Verbindung mit sehr kleinem Widerstand; die Stromstärke wird gefährlich groß.'],
['Ph',8,'Elektrischer Strom','Reihenschaltung','Bauteile hintereinander: Die Stromstärke ist überall gleich, die Spannungen addieren sich.'],
['Ph',8,'Elektrischer Strom','Parallelschaltung','Bauteile nebeneinander: Die Spannung ist überall gleich, die Stromstärken addieren sich.'],
['Ph',8,'Elektrischer Strom','Schaltbild','Zeichnung eines Stromkreises mit genormten Schaltzeichen.'],
['Ph',8,'Optik','Reflexionsgesetz','Einfallswinkel gleich Reflexionswinkel, gemessen zum Lot.'],
['Ph',8,'Optik','Virtuelles Bild','Bild, das nur scheinbar entsteht, etwa hinter dem Spiegel – man kann es nicht auffangen.'],
['Ph',8,'Optik','Reelles Bild','Bild, das sich auf einem Schirm auffangen lässt, z. B. hinter einer Sammellinse.'],
['Ph',8,'Optik','Brechung','Richtungsänderung des Lichts beim Übergang in einen anderen Stoff.'],
['Ph',8,'Optik','Sammellinse','In der Mitte dickere Linse; sie bündelt paralleles Licht im Brennpunkt.'],
['Ph',8,'Optik','Zerstreuungslinse','In der Mitte dünnere Linse; sie lässt paralleles Licht auseinanderlaufen.'],
['Ph',8,'Optik','Brennpunkt','Punkt, in dem eine Sammellinse achsenparallel einfallendes Licht vereinigt.'],
['Ph',8,'Optik','Totalreflexion','Vollständige Rückspiegelung an der Grenzfläche zum optisch dünneren Stoff ab einem Grenzwinkel – Grundlage des Lichtleiters.'],
['Ph',8,'Optik','Lichtleiter','Dünne Faser, in der Licht durch Totalreflexion über weite Strecken geführt wird.'],
['Ph',8,'Mechanik','Geschwindigkeit','v = s / t – zurückgelegter Weg je Zeit; sie hat Betrag und Richtung.'],
['Ph',8,'Mechanik','Zweites Newtonsches Gesetz','F · Δt = m · Δv beziehungsweise F = m · a – Kraft ändert die Geschwindigkeit.'],
['Ph',8,'Mechanik','Kraft','Ursache für Verformung oder Geschwindigkeitsänderung; Einheit Newton (N).'],
['Ph',8,'Mechanik','Beschleunigung','a = Δv / Δt – Geschwindigkeitsänderung je Zeit.'],
['Ph',8,'Mechanik','Trägheit','Eigenschaft eines Körpers, seinen Bewegungszustand beizubehalten; die Masse ist ihr Maß.'],
['Ph',8,'Mechanik','Trägheitsgesetz','Ohne Kraft bleibt ein Körper in Ruhe oder bewegt sich geradlinig-gleichförmig weiter.'],
['Ph',8,'Mechanik','Gewichtskraft','Kraft, mit der ein Körper von der Erde angezogen wird: F_G = m · g.'],
['Ph',8,'Mechanik','Fallbeschleunigung','Beschleunigung im freien Fall, auf der Erde rund 9,81 m/s².'],
['Ph',8,'Mechanik','Kräftegleichgewicht','Alle Kräfte heben sich auf – der Bewegungszustand ändert sich nicht.'],
['Ph',8,'Mechanik','Kräfteaddition','Zusammensetzen von Kräften zu einer Gesamtkraft, zeichnerisch mit Pfeilen.'],
['Ph',8,'Mechanik','Kraftzerlegung','Aufteilen einer Kraft in Komponenten, z. B. Hangabtriebskraft und Normalkraft an der schiefen Ebene.'],
['Ph',8,'Mechanik','Hookesches Gesetz','Im elastischen Bereich ist die Verlängerung einer Feder proportional zur Kraft: F = D · s.'],

/* ================= Physik 9 ================= */
['Ph',9,'Energie','Energie','Größe, die angibt, wie viel ein System an Arbeit verrichten kann; sie geht nie verloren, sondern wandelt sich um. Einheit Joule (J).'],
['Ph',9,'Energie','Energieerhaltung','In einem abgeschlossenen System bleibt die Gesamtenergie gleich – sie ändert nur ihre Form.'],
['Ph',9,'Energie','Kinetische Energie','Bewegungsenergie: E = ½ · m · v².'],
['Ph',9,'Energie','Höhenenergie','Lageenergie im Schwerefeld: E = m · g · h.'],
['Ph',9,'Energie','Spannenergie','In einer gespannten Feder gespeicherte Energie: E = ½ · D · s².'],
['Ph',9,'Energie','Arbeit','Energie, die durch eine Kraft längs eines Weges übertragen wird: W = F · s.'],
['Ph',9,'Energie','Leistung','Energie je Zeit: P = E / t; Einheit Watt (W).'],
['Ph',9,'Energie','Wirkungsgrad','Anteil der zugeführten Energie, der genutzt wird – stets kleiner als 100 %.'],
['Ph',9,'Elektrische Energie','Elementarladung','Kleinste frei vorkommende Ladungsmenge, rund 1,6 · 10⁻¹⁹ C; jede Ladung ist ein Vielfaches davon.'],
['Ph',9,'Elektrische Energie','Elektrische Ladung Q','Q = I · t – Ladungsmenge, die bei der Stromstärke I in der Zeit t fließt; Einheit Coulomb (C).'],
['Ph',9,'Elektrische Energie','Potentialdifferenz','Andere Bezeichnung für die Spannung: Energie je Ladung zwischen zwei Punkten.'],
['Ph',9,'Elektrische Energie','Elektrische Leistung','P = U · I – Produkt aus Spannung und Stromstärke.'],
['Ph',9,'Atome','Photon','Kleinstes Energiepaket des Lichts; seine Energie hängt von der Farbe ab.'],
['Ph',9,'Atome','Energiestufenmodell','Modell, nach dem Atome nur bestimmte Energiewerte annehmen können.'],
['Ph',9,'Atome','Emissionsspektrum','Farben, die ein leuchtendes Gas aussendet – als einzelne Linien sichtbar.'],
['Ph',9,'Atome','Absorptionsspektrum','Dunkle Linien in einem durchgehenden Spektrum: Das Gas hat genau diese Energien verschluckt.'],
['Ph',9,'Atome','Ultraviolettstrahlung','Licht mit höherer Energie als sichtbares Violett – kann Haut und Augen schädigen.'],
['Ph',9,'Atome','Infrarotstrahlung','Licht mit geringerer Energie als sichtbares Rot – wir nehmen es als Wärmestrahlung wahr.'],
['Ph',9,'Wärmelehre','Teilchenmodell','Vorstellung, dass alle Stoffe aus sich ständig bewegenden Teilchen bestehen.'],
['Ph',9,'Wärmelehre','Absolute Temperatur','Temperatur in Kelvin; 0 K ist der absolute Nullpunkt, an dem die Teilchenbewegung minimal ist.'],
['Ph',9,'Wärmelehre','Innere Energie','Summe aus kinetischer und potentieller Energie aller Teilchen eines Körpers.'],
['Ph',9,'Wärmelehre','Aggregatzustand','Erscheinungsform eines Stoffes: fest, flüssig oder gasförmig.'],
['Ph',9,'Wärmelehre','Druck','Kraft je Fläche: p = F / A; im Gas entsteht er durch Teilchenstöße. Einheit Pascal (Pa).'],
['Ph',9,'Wärmelehre','Wärme','Energie, die wegen eines Temperaturunterschieds übertragen wird.'],
['Ph',9,'Wärmelehre','Spezifische Wärmekapazität','Energie, die 1 kg eines Stoffes um 1 K erwärmt; Wasser hat einen besonders großen Wert.'],
['Ph',9,'Wärmelehre','Wärmeleitung','Energietransport durch Stöße benachbarter Teilchen, ohne dass der Stoff strömt.'],
['Ph',9,'Wärmelehre','Konvektion','Energietransport durch strömende Flüssigkeiten oder Gase.'],
['Ph',9,'Wärmelehre','Wärmestrahlung','Energietransport durch Strahlung – sie braucht keinen Stoff und wirkt auch im Vakuum.'],
['Ph',9,'Wärmelehre','Treibhauseffekt','Treibhausgase lassen Sonnenlicht durch, halten aber die Wärmestrahlung der Erde zurück; dadurch steigt die Temperatur.'],
['Ph',9,'Wärmelehre','Strahlungsgleichgewicht','Zustand, in dem die Erde genauso viel Energie abstrahlt, wie sie von der Sonne aufnimmt.'],

/* ================= Physik 10 ================= */
['Ph',10,'Elektromagnetismus','Magnetisches Feld','Raum um einen Magneten oder Strom, in dem Kräfte auf magnetische Körper wirken.'],
['Ph',10,'Elektromagnetismus','Feldlinie','Gedachte Linie, die Richtung und Verlauf eines Feldes anschaulich darstellt.'],
['Ph',10,'Elektromagnetismus','Rechte-Faust-Regel','Daumen in Stromrichtung – die gekrümmten Finger zeigen die Richtung des Magnetfelds um den Leiter.'],
['Ph',10,'Elektromagnetismus','Drei-Finger-Regel','Regel zur Bestimmung der Kraftrichtung auf einen stromdurchflossenen Leiter im Magnetfeld.'],
['Ph',10,'Elektromagnetismus','Lorentzkraft','Kraft auf bewegte Ladungen im Magnetfeld; sie steht senkrecht auf Bewegung und Feld.'],
['Ph',10,'Elektromagnetismus','Elektromotor','Gerät, das elektrische Energie in Bewegungsenergie wandelt – über Kräfte auf stromdurchflossene Leiter.'],
['Ph',10,'Elektromagnetismus','Induktion','Entstehen einer Spannung, wenn sich das Magnetfeld durch eine Spule ändert.'],
['Ph',10,'Elektromagnetismus','Generator','Gerät, das Bewegungsenergie durch Induktion in elektrische Energie wandelt.'],
['Ph',10,'Elektromagnetismus','Transformator','Zwei Spulen auf einem Eisenkern; er ändert Spannung und Stromstärke gegenläufig.'],
['Ph',10,'Impulserhaltung','Impuls','Produkt aus Masse und Geschwindigkeit: p = m · v; er hat eine Richtung.'],
['Ph',10,'Impulserhaltung','Impulserhaltung','In einem abgeschlossenen System bleibt die Summe aller Impulse gleich.'],
['Ph',10,'Impulserhaltung','Wechselwirkungsgesetz','Drittes Newtonsches Gesetz: Kräfte treten stets paarweise auf – actio und reactio an verschiedenen Körpern.'],
['Ph',10,'Impulserhaltung','Elastischer Stoß','Stoß, bei dem außer dem Impuls auch die Bewegungsenergie erhalten bleibt.'],
['Ph',10,'Bewegungen','Zeit-Ort-Diagramm','Diagramm, das zu jedem Zeitpunkt den Ort eines Körpers zeigt; die Steigung ist die Geschwindigkeit.'],
['Ph',10,'Bewegungen','Zeit-Geschwindigkeit-Diagramm','Diagramm der Geschwindigkeit über der Zeit; die Fläche darunter ist der zurückgelegte Weg.'],
['Ph',10,'Bewegungen','Gleichförmige Bewegung','Bewegung mit konstanter Geschwindigkeit: s = v · t.'],
['Ph',10,'Bewegungen','Gleichmäßig beschleunigte Bewegung','Bewegung mit konstanter Beschleunigung: v = a · t und s = ½ · a · t².'],
['Ph',10,'Bewegungen','Freier Fall','Bewegung allein unter der Gewichtskraft, ohne Luftwiderstand.'],
['Ph',10,'Bewegungen','Waagrechter Wurf','Überlagerung einer gleichförmigen waagrechten und einer fallenden senkrechten Bewegung.'],
['Ph',10,'Kernphysik','Radioaktivität','Eigenschaft instabiler Atomkerne, sich unter Aussendung von Strahlung umzuwandeln.'],
['Ph',10,'Kernphysik','Alphastrahlung','Ausgesandte Heliumkerne; sie werden schon von Papier abgeschirmt.'],
['Ph',10,'Kernphysik','Betastrahlung','Ausgesandte Elektronen oder Positronen; sie durchdringen dünnes Metall.'],
['Ph',10,'Kernphysik','Gammastrahlung','Sehr energiereiche Photonen aus dem Kern; sie durchdringen selbst Blei teilweise.'],
['Ph',10,'Kernphysik','Nukleon','Sammelbegriff für Proton und Neutron – die Bausteine des Atomkerns.'],
['Ph',10,'Kernphysik','Quark','Baustein der Nukleonen; Protonen und Neutronen bestehen aus je drei Quarks.'],
['Ph',10,'Kernphysik','Isotop','Atomart mit gleicher Protonenzahl, aber unterschiedlicher Neutronenzahl.'],
['Ph',10,'Kernphysik','Halbwertszeit','Zeit, nach der die Hälfte der Kerne einer Probe zerfallen ist.'],
['Ph',10,'Kernphysik','Äquivalenz von Masse und Energie','E = m · c²: Masse und Energie sind ineinander umwandelbar; daraus stammt die Energie bei Kernreaktionen.'],
['Ph',10,'Kernphysik','Kernspaltung','Zerlegung eines schweren Kerns in leichtere Kerne unter Freisetzung von Energie.'],

/* ================= Physik 11 ================= */
['Ph',11,'Kreisbewegung','Kreisbewegung','Bewegung auf einer Kreisbahn; ihre Geschwindigkeit ändert ständig die Richtung.'],
['Ph',11,'Kreisbewegung','Winkelgeschwindigkeit','Überstrichener Winkel je Zeit: ω = 2π / T.'],
['Ph',11,'Kreisbewegung','Zentripetalkraft','Zum Mittelpunkt gerichtete Kraft, die einen Körper auf der Kreisbahn hält: F = m · v² / r.'],
['Ph',11,'Kreisbewegung','Zentrifugalkraft','Scheinkraft, die nur im mitbewegten Bezugssystem auftritt – nicht zu verwechseln mit der Zentripetalkraft.'],
['Ph',11,'Kreisbewegung','Gravitationsgesetz','Zwei Massen ziehen sich an: F = G · m₁ · m₂ / r².'],
['Ph',11,'Schwingungen und Wellen','Schwingung','Periodische Bewegung um eine Ruhelage, z. B. beim Federpendel.'],
['Ph',11,'Schwingungen und Wellen','Harmonische Schwingung','Schwingung, deren Auslenkung einer Sinuskurve folgt; die rücktreibende Kraft ist proportional zur Auslenkung.'],
['Ph',11,'Schwingungen und Wellen','Periodendauer','Zeit für eine vollständige Schwingung; T = 1 / f.'],
['Ph',11,'Schwingungen und Wellen','Frequenz','Anzahl der Schwingungen je Sekunde; Einheit Hertz (Hz).'],
['Ph',11,'Schwingungen und Wellen','Amplitude','Größte Auslenkung aus der Ruhelage.'],
['Ph',11,'Schwingungen und Wellen','Longitudinalwelle','Welle, bei der die Teilchen in Ausbreitungsrichtung schwingen, z. B. Schall in Luft.'],
['Ph',11,'Schwingungen und Wellen','Transversalwelle','Welle, bei der die Teilchen quer zur Ausbreitungsrichtung schwingen, z. B. auf einer Seilwelle.'],
['Ph',11,'Schwingungen und Wellen','Wellenlänge','Abstand zweier benachbarter gleichphasiger Punkte; es gilt c = λ · f.'],
['Ph',11,'Schwingungen und Wellen','Beugung','Ausbreitung einer Welle in den geometrischen Schattenraum hinter einem Hindernis oder Spalt.'],
['Ph',11,'Schwingungen und Wellen','Interferenz','Überlagerung von Wellen: Sie verstärken oder schwächen sich je nach Gangunterschied.'],
['Ph',11,'Schwingungen und Wellen','Superpositionsprinzip','Regel, dass sich die Auslenkungen überlagernder Wellen einfach addieren.'],
['Ph',11,'Schwingungen und Wellen','Gangunterschied','Wegunterschied zweier Wellen; ganze Vielfache von λ ergeben Verstärkung, ungerade Vielfache von λ/2 Auslöschung.'],
['Ph',11,'Schwingungen und Wellen','Stehende Welle','Schwingungsmuster mit festen Knoten und Bäuchen, entsteht durch Überlagerung hin- und rücklaufender Wellen.'],
['Ph',11,'Schwingungen und Wellen','Doppelspalt','Zwei enge Spalte; das Streifenmuster dahinter zeigt den Wellencharakter des Lichts.'],
['Ph',11,'Schwingungen und Wellen','Welle-Teilchen-Dualismus','Licht zeigt je nach Versuch Wellen- oder Teilcheneigenschaften; beide Modelle ergänzen sich.'],

  ]
};
